name: Echo GET Request Response

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Or your default branch

jobs:
  make-get-request-and-echo-response:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make GET request and echo response
        run: |
          RESPONSE=$(curl -sS "https://stg-usersurveysite-beehivestag.kinsta.cloud/wp-json/wp/v2/apps/2449")
          echo "Response from GET request:"
          echo "$RESPONSE"
