name: Echo GET Request Response with App ID and Store ID

on:
  workflow_dispatch:
    inputs:
      appId:
        description: 'App ID'
        required: true
        default: '2449'  # Set a default value or remove this line if you don't want a default
  push:
    branches:
      - main  # Or your default branch

jobs:
  make-get-request-and-echo-response:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make GET request and store ID
        run: |
          APP_ID="${{ github.event.inputs.appId }}"
          RESPONSE=$(curl -sS "https://stg-usersurveysite-beehivestag.kinsta.cloud/wp-json/wp/v2/apps/${APP_ID}")
          APP_ID=$(echo "$RESPONSE" | jq '.id')
          echo "APP_ID=$APP_ID" >> $GITHUB_ENV

      - name: Echo stored ID
        run: |
          echo "Stored ID: $APP_ID"
