name: Build App

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'App ID'
        required: true
        default: '65ceac31a02e415f4ba6fe55'  # You can adjust the default value as necessary
      jwtToken:
        description: 'JWT Token for Authentication'
        required: true
        default: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2Q5NWM0NzIwNWFhY2NhYjBkOGRlZSIsImlhdCI6MTcwODE0NzE3OSwiZXhwIjoxNzA4MjMzNTc5fQ.UfugeTLzA1AZlcdjE2gKk9KGKMxPjctNJW5mQi580Cg'
jobs:
  make_request_and_store_response:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Curl request and extract _id
        run: |
          RESPONSE=$(curl --location "https://qikmobileapp-3be95504c721.herokuapp.com/get-app?id=${{ github.event.inputs.app_id }}" \
          --header "x-access-token: ${{ github.event.inputs.jwtToken }}")
          echo "Response: $RESPONSE"
          ID=$(echo $RESPONSE | jq -r '._id')
          SOURCE_FILE_BUCKET_KEY=$(echo $RESPONSE | jq -r '.sourceFileBucketKey')
          echo "Extracted _id: $ID"
          echo "SOURCE_FILE_BUCKET_KEY=${SOURCE_FILE_BUCKET_KEY}" >> $GITHUB_ENV
          
      - name: Download Source Code ZIP file
        run: |
          wget "https://source-code-zip-ios.s3.us-west-1.amazonaws.com/${SOURCE_FILE_BUCKET_KEY}" -O src_code.zip

      - name: Unzip the downloaded file
        run: |
          unzip src_code.zip -d src_code

      - name: cd into src
        run: |
          cd ./src_code
          
      - name: List source folder
        run: |
          ls
