name: Make GET Request and Store Response

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'App ID'
        required: true
        default: '2449'  # You can adjust the default value as necessary
      jwtToken:
        description: 'JWT Token for Authentication'
        required: true
        default: ''
jobs:
  make_request_and_store_response:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Curl request and extract _id
        run: |
          RESPONSE=$(curl --location 'http://localhost:3000/get-app?id=65ceac31a02e415f4ba6fe55' \
          --header 'x-access-token: ${{ secrets.ACCESS_TOKEN }}')
          echo "Response: $RESPONSE"
          ID=$(echo $RESPONSE | jq -r '._id')
          echo "Extracted _id: $ID"
   

