name: Make GET Request and Store Response

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  make_request_and_store_response:
    runs-on: ubuntu-latest
    outputs:
      response: ${{ steps.request_step.outputs.response }}
      id: ${{ steps.request_step.outputs.id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make GET request and extract ID
        id: request_step
        run: |
          # Make the GET request
          RESPONSE=$(curl -s "https://stg-usersurveysite-beehivestag.kinsta.cloud/wp-json/wp/v2/apps/2449")
          echo "Full response: $RESPONSE"

          # Extract the ID using jq
          ID=$(echo $RESPONSE | jq '.id')
          echo "Extracted ID: $ID"

          # Set the response and ID as outputs
          echo "::set-output name=response::$RESPONSE"
          echo "::set-output name=id::$ID"

        shell: bash
    
      # Example of using the outputs in the same job (you can also use them in subsequent jobs)
      - name: Use the Outputs
        run: |
          echo "The full response was: ${{ needs.make_request_and_store_response.outputs.response }}"
          echo "The ID extracted was: ${{ needs.make_request_and_store_response.outputs.id }}"
        if: ${{ always() }}  # This ensures it runs even if the previous step fails
