name: Build App

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'App ID'
        required: true
        default: '65ceac31a02e415f4ba6fe55'  # You can adjust the default value as necessary
      jwtToken:
        description: 'JWT Token for Authentication'
        required: true
        default: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2Q5NWM0NzIwNWFhY2NhYjBkOGRlZSIsImlhdCI6MTcwODE0NzE3OSwiZXhwIjoxNzA4MjMzNTc5fQ.UfugeTLzA1AZlcdjE2gKk9KGKMxPjctNJW5mQi580Cg'
jobs:
  make_request_and_store_response:
    name: Ios - Build a new version
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'

      - name: Set up Ruby (Fastlane is a Ruby gem)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Specify the Ruby version you need for your project
          
      - name: Install Fastlane
        run: |
          gem install fastlane

      - name: Curl request and extract _id
        run: |
          RESPONSE=$(curl --location "https://qikmobileapp-3be95504c721.herokuapp.com/get-app?id=${{ github.event.inputs.app_id }}" \
          --header "x-access-token: ${{ github.event.inputs.jwtToken }}")
          echo "Response: $RESPONSE"
          ID=$(echo $RESPONSE | jq -r '._id')
          SOURCE_FILE_BUCKET_KEY=$(echo $RESPONSE | jq -r '.sourceFileBucketKey')
          echo "Extracted _id: $ID"
          echo "SOURCE_FILE_BUCKET_KEY=${SOURCE_FILE_BUCKET_KEY}" >> $GITHUB_ENV
          
      - name: Download Source Code ZIP file
        run: |
          wget "https://source-code-zip-ios.s3.us-west-1.amazonaws.com/${SOURCE_FILE_BUCKET_KEY}" -O src.zip

      - name: Unzip the downloaded file
        run: |
          unzip src.zip -d ios

      - name: Remove MACOSX files
        run: |
          rm -rf __MACOSX
        working-directory: ./ios

      - name: List source folder
        run: |
          ls
        working-directory: ./ios

      - name: Move fastlane folder into ios
        run: |
          cp -rf ../fastlane .
        working-directory: ./ios
        
      - name: List source folder
        run: |
          ls
        working-directory: ./ios

      - name: List fastlane directory
        run: |
          ls
        working-directory: ./ios/fastlane

      - name: List fastlane directory
        run: |
          ls
        working-directory: ./ios/fastlane

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle _2.4.22_ install
        working-directory: ./ios/fastlane

      - name: Run fastlane
        run: |
          bundle exec fastlane build_and_upload_to_s3 scheme:'Chick-fil-a'
        working-directory: ./ios/fastlane
        
