name: Make GET Request and Store Response

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'App ID'
        required: true
        default: '2449'  # You can adjust the default value as necessary
      jwtToken:
        description: 'JWT Token for Authentication'
        required: true
        default: ''
jobs:
  make_request_and_store_response:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Curl request and extract _id
        run: |
          RESPONSE=$(curl --location "https://qikmobileapp-3be95504c721.herokuapp.com/get-app?id=${{ github.event.inputs.app_id }}" \
          --header "x-access-token: ${{ github.event.inputs.jwtToken }}")
          echo "Response: $RESPONSE"
          ID=$(echo $RESPONSE | jq -r '._id')
          echo "Extracted _id: $ID"
   

